general.import = [
  "~/.config/alacritty/alacritty-theme/themes/catpuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
opacity = 0.9
blur = true
startup_mode = "SimpleFullscreen"
resize_increments = true

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 16


[keyboard]
bindings = [
  { key = ",", mods = "Command", command = { program = "sh", args = ["-c","open ~/.config/alacritty/alacritty.toml"] } },
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "Space", mods = "Option", action = "ToggleSimpleFullscreen" },
  { key = ";", mods = "Command", action = "IncreaseFontSize" },
  { key = "-", mods = "Command", action = "DecreaseFontSize" },
]
